{ id: '',
  scope:
   [Object: null prototype] {
     'my module':
      { id: 'my module',
        alphameric: true,
        line_nr: 0,
        column_nr: 4,
        column_to: 13,
        readonly: true,
        origin: [Circular] } },
  zeroth:
   [ { id: 'def',
       alphameric: true,
       line_nr: 0,
       column_nr: 0,
       column_to: 3,
       class: 'statement',
       zeroth:
        { id: 'my module',
          alphameric: true,
          line_nr: 0,
          column_nr: 4,
          column_to: 13,
          readonly: true,
          origin: [Circular] },
       wunth:
        { id: 'module',
          alphameric: false,
          line_nr: 0,
          column_nr: 15,
          column_to: 21,
          scope:
           [Object: null prototype] {
             greet:
              { id: 'greet',
                alphameric: true,
                line_nr: 1,
                column_nr: 8,
                column_to: 13,
                readonly: true,
                origin: [Circular] } },
          parent: [Circular],
          zeroth:
           [ { id: 'def',
               alphameric: true,
               line_nr: 1,
               column_nr: 4,
               column_to: 7,
               class: 'statement',
               zeroth:
                { id: 'greet',
                  alphameric: true,
                  line_nr: 1,
                  column_nr: 8,
                  column_to: 13,
                  readonly: true,
                  origin: [Circular] },
               wunth:
                { id: 'ƒ',
                  line_nr: 1,
                  column_nr: 15,
                  column_to: 16,
                  scope: [Object: null prototype] {},
                  parent: [Circular],
                  zeroth: [],
                  wunth:
                   [ { id: 'return',
                       alphameric: true,
                       line_nr: 2,
                       column_nr: 8,
                       column_to: 14,
                       class: 'statement',
                       zeroth:
                        { id: '(text)',
                          readonly: true,
                          text: 'hello world',
                          line_nr: 2,
                          column_nr: 15,
                          column_to: 28 },
                       disrupt: true,
                       return: true },
                     disrupt: true,
                     return: true ] } },
             disrupt: undefined,
             return: undefined ] } } ] }